# This file generates the GitHub Actions matrix.
#
# My kain keyboard which is using nice_nano_v2 compatible Pro Micro
# NRF52840.  Hand wired using the Narfkb2 plates.  I'm wiring the
# thumb keys similar to a Corne, but using my own pin assignments.

---
include:
  - board: nice_nano_v2
    shield: kain_left
  - board: nice_nano_v2
    shield: kain_right
